#!/bin/bash
wget https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml

kubectl apply -f recommended.yaml

#get port
kubectl get services  -n kube-system
#login
https://master-ip:port
