#!/bin/bash

#conda install pyspark kernel
ipython kernel install  --name pyspark

#python2 install ipykernel
pip install ipykernel
echo "{
 "display_name": "pySpark",
 "language": "python",
 "argv": [
  "/usr/bin/python2",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "SPARK_HOME": "/opt/spark-2.3.4-bin-hadoop2.7/",
  "PYTHONPATH": "/opt/spark-2.3.4-bin-hadoop2.7/python:/opt/spark-2.3.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip",
  "PYTHONSTARTUP": "/opt/spark-2.3.4-bin-hadoop2.7/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "pyspark-shell"
  }
}
">&/usr/local/share/jupyter/kernels/pyspark/kernel.json