#!/bin/bash
kubeadm init --kubernetes-version=v1.13.3 --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.83.66 --ignore-preflight-errors=NumCPU
#apiserver-advertise-address master-ip

sudo cp /etc/kubernetes/admin.conf $HOME
sudo chown $(id -u):$(id -g) $HOME/admin.conf
export KUBECONFIG=$HOME/admin.conf
echo "export KUBECONFIG=$HOME/admin.conf" >> $HOME/.bashrc

#scp config file to node
scp /etc/sysconfig/kubelet node2:/etc/sysconfig/kubelet
